-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.category
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.image
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    data bytea,
    CONSTRAINT pk_nama PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    image character varying(255) COLLATE pg_catalog."default" DEFAULT 'default.png'::character varying,
    sell_price numeric NOT NULL DEFAULT 0,
    buy_price numeric NOT NULL DEFAULT 0,
    category_id integer NOT NULL DEFAULT nextval('product_categoryid_seq'::regclass),
    amount integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'Asia/Jakarta'::text),
    updated_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'Asia/Jakarta'::text),
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    fullname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    image character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'Asia/Jakarta'::text),
    updated_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'Asia/Jakarta'::text),
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT user_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT fk_image FOREIGN KEY (image)
    REFERENCES public.image (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_categoryid_fkey FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;